<a href="https://colab.research.google.com/github/ramanujdixit/Applied_Data_Science/blob/main/05/22/2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
name = "Ramanuj"
age = 20
print(name, age)

Ramanuj 20


In [ ]:
X="Datascience is used to extract meaningful insights."
X.split()

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [ ]:
def mul(x,y):
  return x*y

In [ ]:
print(mul(8,9))

72


In [ ]:
dictionary={"Madhya Pradesh":"Bhopal","Chhattisgarh":"Raipur","Himachal pradesh":"Shimla","Gujarat":"Gandhinagar","Uttar Pradesh":"Lucknow"}

In [ ]:
print(dictionary.keys())

dict_keys(['Madhya Pradesh', 'Chhattisgarh', 'Himachal pradesh', 'Gujarat', 'Uttar Pradesh'])


In [ ]:
print(dictionary.values())

dict_values(['Bhopal', 'Raipur', 'Shimla', 'Gandhinagar', 'Lucknow'])


In [ ]:
num=[]
for i in range(1000):
  num.append(i)

In [ ]:
print(num)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [ ]:
a=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
for i in range(4):
  for j in range(4):
    if i==j:
      a[i][j]=1

In [ ]:
print(a)

[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


In [ ]:
import random

matrix = [[random.randint(1, 9) for _ in range(3)] for _ in range(3)]

for row in matrix:
    print(row)


[5, 3, 2]
[4, 1, 8]
[8, 9, 2]


In [ ]:
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

result = array1 + array2
print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

current_date = start_date
while current_date <= end_date:
    print(current_date.strftime("%d-%m-%Y"))
    current_date += timedelta(days=1)


01-02-2023
02-02-2023
03-02-2023
04-02-2023
05-02-2023
06-02-2023
07-02-2023
08-02-2023
09-02-2023
10-02-2023
11-02-2023
12-02-2023
13-02-2023
14-02-2023
15-02-2023
16-02-2023
17-02-2023
18-02-2023
19-02-2023
20-02-2023
21-02-2023
22-02-2023
23-02-2023
24-02-2023
25-02-2023
26-02-2023
27-02-2023
28-02-2023
01-03-2023


In [ ]:
import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}

df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
